
version: "3"
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=my_cool_secret
      - MARIADB_ROOT_PASSWORD=my-secret-pw
      - MARIADB_DATABASE=wordpress
   # ports:
   #   - "3306:3306"
    volumes:
      - ./mariadb-data/:/var/lib/mysql/
  #apache2.4:
    #image: httpd:2.4
    #ports:
     # - "80:80"
    #volumes:
      #- ./http/:/usr/local/apache2/htdocs/
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: example-user
      WORDPRESS_DB_PASSWORD: my_cool_secret
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress/:/var/www/html/
